/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.UI.HangHoa;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import src.Model.ChiTietPhieuNhapHang;
import src.Model.PhieuNhapHang;
import src.Service.ChiTietPhieuNhapHangService;
import src.Util.Util;

/**
 *
 * @author WINDOWS 10
 */
public class frame_ChiTietDonNhapHang extends javax.swing.JFrame {
    private ChiTietPhieuNhapHangService chiTietPhieuNhapHangService = new ChiTietPhieuNhapHangService();
    private PhieuNhapHang phieuNhapHang;
    private Util util = new Util();

    public PhieuNhapHang getPhieuNhapHang() {
        return phieuNhapHang;
    }

    public void setPhieuNhapHang(PhieuNhapHang phieuNhapHang) {
        this.phieuNhapHang = phieuNhapHang;
    }
    
    /**
     * Creates new form frame_HoaDonChiTiet
     */
    public frame_ChiTietDonNhapHang() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        hienThiThongTinPhieuNhapHang();
        try {
            hienThiDanhSachChiTietPhieuNhapHangTheoMaPhieuNhapHang(this.phieuNhapHang.getPhieuNhapHang());
        } catch (SQLException ex) {
            Logger.getLogger(frame_ChiTietDonNhapHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public frame_ChiTietDonNhapHang(PhieuNhapHang phieuNhapHang) {
        this.phieuNhapHang = phieuNhapHang;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        hienThiThongTinPhieuNhapHang();
        try {
            hienThiDanhSachChiTietPhieuNhapHangTheoMaPhieuNhapHang(this.phieuNhapHang.getPhieuNhapHang());
        } catch (SQLException ex) {
            Logger.getLogger(frame_ChiTietDonNhapHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel239 = new javax.swing.JPanel();
        btn_capNhat = new javax.swing.JButton();
        btn_traHangNhap = new javax.swing.JButton();
        btn_in = new javax.swing.JButton();
        btn_huyBo = new javax.swing.JButton();
        jPanel241 = new javax.swing.JPanel();
        jLabel287 = new javax.swing.JLabel();
        lb_maNhapHang = new javax.swing.JLabel();
        jPanel242 = new javax.swing.JPanel();
        jLabel289 = new javax.swing.JLabel();
        lb_tongTienHang = new javax.swing.JLabel();
        jPanel243 = new javax.swing.JPanel();
        jLabel291 = new javax.swing.JLabel();
        lb_tenNguoiTao = new javax.swing.JLabel();
        jPanel244 = new javax.swing.JPanel();
        jLabel293 = new javax.swing.JLabel();
        lb_tienDaTra = new javax.swing.JLabel();
        jPanel245 = new javax.swing.JPanel();
        jLabel295 = new javax.swing.JLabel();
        cb_nhaCungCap = new javax.swing.JComboBox<>();
        jScrollPane15 = new javax.swing.JScrollPane();
        tb_chiTietDonNhapHang = new javax.swing.JTable();
        jPanel246 = new javax.swing.JPanel();
        jLabel297 = new javax.swing.JLabel();
        lb_tenChiNhanh = new javax.swing.JLabel();
        jPanel247 = new javax.swing.JPanel();
        jLabel299 = new javax.swing.JLabel();
        lb_noNhaCungCap = new javax.swing.JLabel();
        jPanel248 = new javax.swing.JPanel();
        jLabel301 = new javax.swing.JLabel();
        lb_thoiGian = new javax.swing.JLabel();
        jPanel249 = new javax.swing.JPanel();
        jLabel303 = new javax.swing.JLabel();
        cb_nhaCungCap1 = new javax.swing.JComboBox<>();
        jPanel250 = new javax.swing.JPanel();
        jLabel305 = new javax.swing.JLabel();
        lb_tongSoLuong = new javax.swing.JLabel();
        jPanel251 = new javax.swing.JPanel();
        jLabel307 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel252 = new javax.swing.JPanel();
        jLabel304 = new javax.swing.JLabel();
        lb_nhaCungCapNo = new javax.swing.JLabel();
        jLabel296 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel239.setBackground(new java.awt.Color(255, 255, 255));
        jPanel239.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_capNhat.setBackground(new java.awt.Color(51, 204, 0));
        btn_capNhat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_capNhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_capNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        btn_capNhat.setText("Cập nhật");
        jPanel239.add(btn_capNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 555, -1, -1));

        btn_traHangNhap.setBackground(new java.awt.Color(51, 204, 0));
        btn_traHangNhap.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_traHangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_traHangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/return2.png"))); // NOI18N
        btn_traHangNhap.setText("Trả hàng nhập");
        jPanel239.add(btn_traHangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 554, 157, -1));

        btn_in.setBackground(new java.awt.Color(51, 204, 0));
        btn_in.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_in.setForeground(new java.awt.Color(255, 255, 255));
        btn_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exportFile.png"))); // NOI18N
        btn_in.setText("In");
        jPanel239.add(btn_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 555, -1, -1));

        btn_huyBo.setBackground(new java.awt.Color(255, 51, 51));
        btn_huyBo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_huyBo.setForeground(new java.awt.Color(255, 255, 255));
        btn_huyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        btn_huyBo.setText("Hủy bỏ");
        btn_huyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyBoActionPerformed(evt);
            }
        });
        jPanel239.add(btn_huyBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 555, -1, -1));

        jPanel241.setBackground(new java.awt.Color(255, 255, 255));

        jLabel287.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel287.setText("Mã nhập hàng:");

        lb_maNhapHang.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_maNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_maNhapHang.setText("lb_maNhapHang");

        javax.swing.GroupLayout jPanel241Layout = new javax.swing.GroupLayout(jPanel241);
        jPanel241.setLayout(jPanel241Layout);
        jPanel241Layout.setHorizontalGroup(
            jPanel241Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel241Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel287)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_maNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel241Layout.setVerticalGroup(
            jPanel241Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel241Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel241Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel287)
                    .addComponent(lb_maNhapHang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel241, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 7, 256, -1));

        jPanel242.setBackground(new java.awt.Color(255, 255, 255));

        jLabel289.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel289.setText("Tổng tiền hàng:");

        lb_tongTienHang.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_tongTienHang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_tongTienHang.setText("16,926,700");

        javax.swing.GroupLayout jPanel242Layout = new javax.swing.GroupLayout(jPanel242);
        jPanel242.setLayout(jPanel242Layout);
        jPanel242Layout.setHorizontalGroup(
            jPanel242Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel242Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel289)
                .addGap(18, 18, 18)
                .addComponent(lb_tongTienHang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel242Layout.setVerticalGroup(
            jPanel242Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel242Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel242Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel289)
                    .addComponent(lb_tongTienHang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel242, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 472, -1, -1));

        jPanel243.setBackground(new java.awt.Color(255, 255, 255));

        jLabel291.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel291.setText("Người tạo:");

        lb_tenNguoiTao.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lb_tenNguoiTao.setText("Nguyễn Thị Thúy Hòa");

        javax.swing.GroupLayout jPanel243Layout = new javax.swing.GroupLayout(jPanel243);
        jPanel243.setLayout(jPanel243Layout);
        jPanel243Layout.setHorizontalGroup(
            jPanel243Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel243Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel291)
                .addGap(60, 60, 60)
                .addComponent(lb_tenNguoiTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel243Layout.setVerticalGroup(
            jPanel243Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel243Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel243Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel291)
                    .addComponent(lb_tenNguoiTao))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel243, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 316, -1));

        jPanel244.setBackground(new java.awt.Color(255, 255, 255));

        jLabel293.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel293.setText("Tiền đã trả:");

        lb_tienDaTra.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_tienDaTra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_tienDaTra.setText("16,926,700");

        javax.swing.GroupLayout jPanel244Layout = new javax.swing.GroupLayout(jPanel244);
        jPanel244.setLayout(jPanel244Layout);
        jPanel244Layout.setHorizontalGroup(
            jPanel244Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel244Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel293)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_tienDaTra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel244Layout.setVerticalGroup(
            jPanel244Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel244Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel244Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel293)
                    .addComponent(lb_tienDaTra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel244, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 434, -1, -1));

        jPanel245.setBackground(new java.awt.Color(255, 255, 255));

        jLabel295.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel295.setText("Nhà cung cấp:");

        cb_nhaCungCap.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel245Layout = new javax.swing.GroupLayout(jPanel245);
        jPanel245.setLayout(jPanel245Layout);
        jPanel245Layout.setHorizontalGroup(
            jPanel245Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel245Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel295)
                .addGap(27, 27, 27)
                .addComponent(cb_nhaCungCap, 0, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel245Layout.setVerticalGroup(
            jPanel245Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel245Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel245Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel295)
                    .addComponent(cb_nhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel245, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        tb_chiTietDonNhapHang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tb_chiTietDonNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã chi tiết", "Mã hàng", "Tên hàng", "Số lượng", "Giá nhập", "Tổng", "Giảm giá", "Thành tiền"
            }
        ));
        tb_chiTietDonNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_chiTietDonNhapHangMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(tb_chiTietDonNhapHang);

        jPanel239.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 166, 901, 262));

        jPanel246.setBackground(new java.awt.Color(255, 255, 255));

        jLabel297.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel297.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel297.setText("Chi nhánh:");

        lb_tenChiNhanh.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lb_tenChiNhanh.setText("Chi nhánh trung tâm");

        javax.swing.GroupLayout jPanel246Layout = new javax.swing.GroupLayout(jPanel246);
        jPanel246.setLayout(jPanel246Layout);
        jPanel246Layout.setHorizontalGroup(
            jPanel246Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel246Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel297)
                .addGap(62, 62, 62)
                .addComponent(lb_tenChiNhanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel246Layout.setVerticalGroup(
            jPanel246Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel246Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel246Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel297)
                    .addComponent(lb_tenChiNhanh))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel246, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 316, -1));

        jPanel247.setBackground(new java.awt.Color(255, 255, 255));

        jLabel299.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel299.setText("Nợ nhà cung cấp:");

        lb_noNhaCungCap.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_noNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_noNhaCungCap.setText("0");

        javax.swing.GroupLayout jPanel247Layout = new javax.swing.GroupLayout(jPanel247);
        jPanel247.setLayout(jPanel247Layout);
        jPanel247Layout.setHorizontalGroup(
            jPanel247Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel247Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel299)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_noNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel247Layout.setVerticalGroup(
            jPanel247Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel247Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel247Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel299)
                    .addComponent(lb_noNhaCungCap))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel247, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 472, -1, -1));

        jPanel248.setBackground(new java.awt.Color(255, 255, 255));

        jLabel301.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel301.setText("Thời gian:");

        lb_thoiGian.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lb_thoiGian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_thoiGian.setText("03/03/2024 10:29");

        javax.swing.GroupLayout jPanel248Layout = new javax.swing.GroupLayout(jPanel248);
        jPanel248.setLayout(jPanel248Layout);
        jPanel248Layout.setHorizontalGroup(
            jPanel248Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel248Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel301)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_thoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel248Layout.setVerticalGroup(
            jPanel248Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel248Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel248Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel301)
                    .addComponent(lb_thoiGian))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel248, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 256, -1));

        jPanel249.setBackground(new java.awt.Color(255, 255, 255));

        jLabel303.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel303.setText("Trạng thái:");

        cb_nhaCungCap1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cb_nhaCungCap1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa nhập hàng", "Đã nhập hàng", "Đã thanh toán" }));

        javax.swing.GroupLayout jPanel249Layout = new javax.swing.GroupLayout(jPanel249);
        jPanel249.setLayout(jPanel249Layout);
        jPanel249Layout.setHorizontalGroup(
            jPanel249Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel249Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel303)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(cb_nhaCungCap1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel249Layout.setVerticalGroup(
            jPanel249Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel249Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel249Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel303)
                    .addComponent(cb_nhaCungCap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel249, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 4, -1, -1));

        jPanel250.setBackground(new java.awt.Color(255, 255, 255));

        jLabel305.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel305.setText("Tổng số lượng:");

        lb_tongSoLuong.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_tongSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_tongSoLuong.setText("21");

        javax.swing.GroupLayout jPanel250Layout = new javax.swing.GroupLayout(jPanel250);
        jPanel250.setLayout(jPanel250Layout);
        jPanel250Layout.setHorizontalGroup(
            jPanel250Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel250Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel305)
                .addGap(18, 18, 18)
                .addComponent(lb_tongSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel250Layout.setVerticalGroup(
            jPanel250Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel250Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel250Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel305)
                    .addComponent(lb_tongSoLuong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel250, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 434, 277, -1));

        jPanel251.setBackground(new java.awt.Color(255, 255, 255));

        jLabel307.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel307.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil.png"))); // NOI18N

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Ghi chú...");
        jScrollPane16.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel251Layout = new javax.swing.GroupLayout(jPanel251);
        jPanel251.setLayout(jPanel251Layout);
        jPanel251Layout.setHorizontalGroup(
            jPanel251Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel251Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel307)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel251Layout.setVerticalGroup(
            jPanel251Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel251Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel307)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jPanel239.add(jPanel251, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 16, -1, -1));

        jPanel252.setBackground(new java.awt.Color(255, 255, 255));

        jLabel304.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel304.setText("Nhà cung cấp nợ:");

        lb_nhaCungCapNo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_nhaCungCapNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_nhaCungCapNo.setText("0");

        javax.swing.GroupLayout jPanel252Layout = new javax.swing.GroupLayout(jPanel252);
        jPanel252.setLayout(jPanel252Layout);
        jPanel252Layout.setHorizontalGroup(
            jPanel252Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel252Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel304)
                .addGap(24, 24, 24)
                .addComponent(lb_nhaCungCapNo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel252Layout.setVerticalGroup(
            jPanel252Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel252Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel252Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel304)
                    .addComponent(lb_nhaCungCapNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel239.add(jPanel252, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 510, -1, -1));

        jLabel296.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel296.setForeground(new java.awt.Color(102, 102, 102));
        jLabel296.setText("Chỉnh sửa chi tiết đơn đặt hàng bằng cách chọn tương ứng");
        jPanel239.add(jLabel296, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel239, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel239, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_huyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyBoActionPerformed
        // close the frame
        this.dispose();
    }//GEN-LAST:event_btn_huyBoActionPerformed

    private void tb_chiTietDonNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_chiTietDonNhapHangMouseClicked
        int index = tb_chiTietDonNhapHang.getSelectedRow();
        TableModel model = tb_chiTietDonNhapHang.getModel();
        ChiTietPhieuNhapHang chiTietPhieuNhapHang = new ChiTietPhieuNhapHang();
        try {
            chiTietPhieuNhapHang = chiTietPhieuNhapHangService.hienThiChiTietPhieuNhapHangTheoMaChiTietPhieuNhapHang(model.getValueAt(index, 0).toString());
        } catch (SQLException ex) {
            Logger.getLogger(frame_ChiTietDonNhapHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        Frame_CapNhatChiTietDonNhapHang frame_CapNhatChiTietDonNhapHang = new Frame_CapNhatChiTietDonNhapHang(chiTietPhieuNhapHang);
        frame_CapNhatChiTietDonNhapHang.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame_CapNhatChiTietDonNhapHang.setVisible(true);
        frame_CapNhatChiTietDonNhapHang.setSize(300, 352);
        frame_CapNhatChiTietDonNhapHang.setLocation(250,250);
        frame_CapNhatChiTietDonNhapHang.addCloseEventListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    // Execute your function when the Frame_CapNhatChiTietDonNhapHang frame is closed
                    hienThiDanhSachChiTietPhieuNhapHangTheoMaPhieuNhapHang(phieuNhapHang.getPhieuNhapHang());
                } catch (SQLException ex) {
                    Logger.getLogger(frame_ChiTietDonNhapHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
});
    }//GEN-LAST:event_tb_chiTietDonNhapHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_ChiTietDonNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_ChiTietDonNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_ChiTietDonNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_ChiTietDonNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_ChiTietDonNhapHang().setVisible(true);
            }
        });
    }
    
    public void hienThiDanhSachChiTietPhieuNhapHangTheoMaPhieuNhapHang(String maPhieuNhapHang) throws SQLException{
        DefaultTableModel recordTable = (DefaultTableModel)tb_chiTietDonNhapHang.getModel();
        recordTable.setRowCount(0);
        List<ChiTietPhieuNhapHang> danhChiTietPhieuNhapHang = chiTietPhieuNhapHangService.hienThiChiTietPhieuNhapHangTheoMaPhieuNhapHang(maPhieuNhapHang);
        short tongSoLuong = 0;
        double tongTienHang = 0;
        for (ChiTietPhieuNhapHang chiTietPhieuNhapHang : danhChiTietPhieuNhapHang) {
            Vector columnData = new Vector();
            columnData.add(chiTietPhieuNhapHang.getMaChiTietPhieuNhapHang());
            columnData.add(chiTietPhieuNhapHang.getMaHangHoa());
            columnData.add(chiTietPhieuNhapHang.getHangHoa().getTenHangHoa());
            columnData.add(chiTietPhieuNhapHang.getSo_luong());
            columnData.add(chiTietPhieuNhapHang.getGia_nhap());
            columnData.add(chiTietPhieuNhapHang.getTong());
            columnData.add(chiTietPhieuNhapHang.getGiam_gia());
            columnData.add(chiTietPhieuNhapHang.getThanh_tien());
            recordTable.addRow(columnData);
            tongTienHang += chiTietPhieuNhapHang.getTong();
            tongSoLuong += chiTietPhieuNhapHang.getSo_luong();
        }
        lb_tongSoLuong.setText(String.valueOf(tongSoLuong));
        lb_tongTienHang.setText(String.valueOf(tongTienHang));
        if (tongTienHang > this.phieuNhapHang.getTienDaTra()){
            lb_noNhaCungCap.setText(String.valueOf(tongTienHang - this.phieuNhapHang.getTienDaTra()));
        }
        if (tongTienHang < this.phieuNhapHang.getTienDaTra()){
            lb_noNhaCungCap.setText(String.valueOf(this.phieuNhapHang.getTienDaTra() - tongTienHang));
        }
    }
    public void hienThiThongTinPhieuNhapHang(){
        lb_maNhapHang.setText(this.phieuNhapHang.getPhieuNhapHang());
        lb_tenChiNhanh.setText(this.phieuNhapHang.getMaChiNhanh());
        lb_tenNguoiTao.setText(this.phieuNhapHang.getMaNhanVienTao());
//        lb_tenNhaCungCap.setText(this.phieuNhapHang.getMaNhaCungCap());
        lb_thoiGian.setText(util.localDateParseMethod(this.phieuNhapHang.getThoiGian()));
//        lb_trangThai.setText(this.phieuNhapHang.getTrangThai());
        lb_tienDaTra.setText(String.valueOf(this.phieuNhapHang.getTienDaTra()));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_huyBo;
    private javax.swing.JButton btn_in;
    private javax.swing.JButton btn_traHangNhap;
    private javax.swing.JComboBox<String> cb_nhaCungCap;
    private javax.swing.JComboBox<String> cb_nhaCungCap1;
    private javax.swing.JLabel jLabel287;
    private javax.swing.JLabel jLabel289;
    private javax.swing.JLabel jLabel291;
    private javax.swing.JLabel jLabel293;
    private javax.swing.JLabel jLabel295;
    private javax.swing.JLabel jLabel296;
    private javax.swing.JLabel jLabel297;
    private javax.swing.JLabel jLabel299;
    private javax.swing.JLabel jLabel301;
    private javax.swing.JLabel jLabel303;
    private javax.swing.JLabel jLabel304;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JPanel jPanel239;
    private javax.swing.JPanel jPanel241;
    private javax.swing.JPanel jPanel242;
    private javax.swing.JPanel jPanel243;
    private javax.swing.JPanel jPanel244;
    private javax.swing.JPanel jPanel245;
    private javax.swing.JPanel jPanel246;
    private javax.swing.JPanel jPanel247;
    private javax.swing.JPanel jPanel248;
    private javax.swing.JPanel jPanel249;
    private javax.swing.JPanel jPanel250;
    private javax.swing.JPanel jPanel251;
    private javax.swing.JPanel jPanel252;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lb_maNhapHang;
    private javax.swing.JLabel lb_nhaCungCapNo;
    private javax.swing.JLabel lb_noNhaCungCap;
    private javax.swing.JLabel lb_tenChiNhanh;
    private javax.swing.JLabel lb_tenNguoiTao;
    private javax.swing.JLabel lb_thoiGian;
    private javax.swing.JLabel lb_tienDaTra;
    private javax.swing.JLabel lb_tongSoLuong;
    private javax.swing.JLabel lb_tongTienHang;
    private javax.swing.JTable tb_chiTietDonNhapHang;
    // End of variables declaration//GEN-END:variables
}
